name: Regenerate Docs
on:
  workflow_dispatch:
jobs:
  build-with-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          NODE_VERSION=$(awk -F'"' '/node =/ {print $2}' .mise.toml)
          echo "NODE_VERSION=$NODE_VERSION" >> $GITHUB_ENV
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: ${{ env.NODE_VERSION }}
          registry-url: "https://registry.npmjs.org"
      - run: pnpm install --frozen-lockfile
      - run: pnpm eslint:check
      - run: pnpm prettier:check
      - run: pnpm build
      - run: pnpm test
      - run: pnpm build:docs
      - uses: actions/upload-pages-artifact@v3
        id: deployment
        with:
          path: docs/

  publish-docs:
    needs: build-with-docs
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/deploy-pages@v4
