name: Publish Release
on:
  push:
    tags:
      - "v*" # e.g. v1.2.3
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          NODE_VERSION=$(awk -F'"' '/node =/ {print $2}' .mise.toml)
          echo "NODE_VERSION=$NODE_VERSION" >> $GITHUB_ENV
          corepack enable
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: ${{ env.NODE_VERSION }}
          registry-url: "https://registry.npmjs.org"
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint:ci
      - run: pnpm build
      - run: pnpm test
      - run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
