name: Lint & Build & Test
on:
  push:
    branches:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          NODE_VERSION=$(awk -F'"' '/node =/ {print $2}' .mise.toml)
          echo "NODE_VERSION=$NODE_VERSION" >> $GITHUB_ENV
          corepack enable
      - uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: ${{ env.NODE_VERSION }}
      - run: pnpm install --frozen-lockfile
      - run: pnpm lint:ci
      - run: pnpm build
      - run: pnpm test
      - run: pnpm build:docs
